default_platform(:android)

platform :android do

  desc "beta 배포"
  lane :beta do

    ENV["JAVA_HOME"] = "E:/java/jdk-17.0.19"
    ENV["PATH"] = "#{ENV['JAVA_HOME']}/bin;#{ENV['PATH']}"

    # Release Bundle 생성(AAB)
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    # Google Play Internal Track 업로드
    upload_to_play_store(
      track: "beta",
      release_status: "draft",
      metadata_path: "./fastlane/metadata",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: false
    )

    puts "Beta 배포 완료"

  end

  desc "Production 배포"
  lane :production do

    ENV["JAVA_HOME"] = "E:/java/jdk-17.0.19"
    ENV["PATH"] = "#{ENV['JAVA_HOME']}/bin;#{ENV['PATH']}"

    # Release Bundle 생성(AAB)
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    # Play Store Production 업로드
    upload_to_play_store(
      track: "production",
      # release_status: "draft", // 임시 제출
      release_status: "completed", #// 바로 심사 제출
      metadata_path: "./fastlane/metadata/android",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: false
      # changes_not_sent_for_review: true // 변경사항 검토 하고 심사제출 할건지 여부
    )
    puts "Production 배포 완료"
  end

end
